version: '3.8'

services:
  expense:
    container_name: expense-monitor
    ports:
      - "5000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    depends_on:
      - database
  
  database:
    container_name: expense-database
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    